### ISSUE TITLE
Design layouts

### ISSUE THREAD

**Issue by Baakoma** [Where-Have-I-Been/Where-Have-I-Been-Client#4]
- [x] Homepage 
- [x] Login/Register forms
- [x] User profile
- [x] User public profile
- [x] Feed/Dashboard
- [x] Trip creator views  
- [x] Trip view
- [x] Social panel (users and trips)
- [x] Statistics

**Comment by Blusia** [comment]
![logowanie – 5](https://user-images.githubusercontent.com/61757744/101797392-464b8c00-3b0a-11eb-8c17-c7f0d6150bee.png)
![logowanie – 6](https://user-images.githubusercontent.com/61757744/101797411-4ba8d680-3b0a-11eb-9858-094f426b95d0.png)

**Comment by Blusia** [comment]
User public profile -mockup 
![profil – 10](https://user-images.githubusercontent.com/61757744/102247596-70cd8880-3f00-11eb-8d57-de1bf77a057e.png)

**Comment by Blusia** [comment]
User profile settings - mockup 
![1](https://user-images.githubusercontent.com/61757744/102261629-3c62c800-3f12-11eb-9afd-8ae78027407b.png)
![2](https://user-images.githubusercontent.com/61757744/102261634-3d93f500-3f12-11eb-86a3-2530dbe2533f.png)
![3](https://user-images.githubusercontent.com/61757744/102261638-3ec52200-3f12-11eb-921c-26f1af5e2d8e.png)
![4](https://user-images.githubusercontent.com/61757744/102261644-3ff64f00-3f12-11eb-824b-f6bb151f86de.png)
![5](https://user-images.githubusercontent.com/61757744/102261648-41c01280-3f12-11eb-8e3e-9d393292e218.png)

**Comment by Blusia** [comment]
Homepage -mockup
![NL](https://user-images.githubusercontent.com/61757744/102351374-9f9e3a00-3fa6-11eb-888b-6f7996004011.png)

**Comment by Blusia** [comment]
Feed - mockup 
![feed](https://user-images.githubusercontent.com/61757744/104096324-255a9000-529c-11eb-8f72-b434a16eb8b3.png)

**Comment by Blusia** [comment]
Social panel (users and trips) - mockup 
![katalogi](https://user-images.githubusercontent.com/61757744/104100787-83d43e00-529d-11eb-8390-82706705d749.png)
![katalogi – 1](https://user-images.githubusercontent.com/61757744/104100800-846cd480-529d-11eb-838e-63dd1f15a205.png)

**Comment by Blusia** [comment]
Trip creator views  - mockup (incomplete set)
![2 usuwanie](https://user-images.githubusercontent.com/61757744/104101523-bda54480-529d-11eb-90db-2a60b35a3e47.png)
![1 moje wycieczki](https://user-images.githubusercontent.com/61757744/104101533-be3ddb00-529d-11eb-8762-bae94391eb2f.png)
![edycja](https://user-images.githubusercontent.com/61757744/104101557-c0079e80-529d-11eb-8535-0583f894e1df.png)

**Comment by Blusia** [comment]
Statistic - mockup 
![profil – 11](https://user-images.githubusercontent.com/61757744/104940412-fafe8600-59b1-11eb-9487-4fb67bfa7c57.png)
