### ISSUE TITLE
Select CSS Framework

### ISSUE THREAD

**Issue by Baakoma** [Where-Have-I-Been/Where-Have-I-Been-Client#5]
- https://bulma.io/
- https://getbootstrap.com/
- https://get.foundation/
- https://semantic-ui.com/
- https://materializecss.com/

**Comment by rewe999** [comment]
Bulma would be good for this project, but bootstrap has more templates and more useful components. I think bootstrap will be the best.

**Comment by Baakoma** [comment]
@rewe999 Which Bootstrap version?

**Comment by rewe999** [comment]
@Baakoma I have chosen versions 5.0
